/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class control_JavaFuzzyControl */

#ifndef _Included_control_JavaFuzzyControl
#define _Included_control_JavaFuzzyControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     control_JavaFuzzyControl
 * Method:    getFuzzyControlDelta
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_control_JavaFuzzyControl_getFuzzyControlDelta
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     control_JavaFuzzyControl
 * Method:    getFuzzyControlLambda
 * Signature: (IIDD)D
 */
JNIEXPORT jdouble JNICALL Java_control_JavaFuzzyControl_getFuzzyControlLambda
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
